services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: enterprise-rag-sql
    user: "0:0"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=YourStrong@Pass123!
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql/data

  qdrant:
    image: qdrant/qdrant:latest
    container_name: enterprise-rag-qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage

volumes:
  sql_data:
  qdrant_data: