<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Core\EnterpriseRag.Core.Application\EnterpriseRag.Core.Application.csproj" />
    <ProjectReference Include="..\..\Infrastructure\EnterpriseRag.Infrastructure.Persistence\EnterpriseRag.Infrastructure.Persistence.csproj" />
    <ProjectReference Include="..\..\Infrastructure\EnterpriseRag.Infrastructure.Identity\EnterpriseRag.Infrastructure.Identity.csproj" />
    <ProjectReference Include="..\..\Infrastructure\EnterpriseRag.Infrastructure.Shared\EnterpriseRag.Infrastructure.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.*" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="9.*" />
  </ItemGroup>

</Project>
